force_light_ext:
  name: Force eclairage exterieur
  initial: off

piscine_marche_force:
  name: Piscine en marche forc√©
  initial: off
  icon: mdi:pool

notification_onduleur:
  name: Notification Onduleur
  initial: on
  icon: mdi:car-battery